<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="myzilla" nsURI="http://myzilla/1.0" nsPrefix="myzilla">
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Classification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="products" upperBound="-1"
        eType="#//Product" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="versions" upperBound="-1"
        eType="#//Version" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Version">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="myzillas" upperBound="-1"
        eType="#//Myzilla" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Myzilla">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bugID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="severity" lowerBound="1"
        eType="#//Severity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" lowerBound="1"
        eType="#//Priority"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" lowerBound="1"
        eType="#//Status"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resolution" eType="#//Resolution"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reporter" lowerBound="1"
        eType="#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignee" eType="#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comments" upperBound="-1"
        eType="#//Comment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="commenter" lowerBound="1"
        eType="#//User"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="when" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Severity">
    <eLiterals name="enhancement"/>
    <eLiterals name="trivial" value="1"/>
    <eLiterals name="minor" value="2"/>
    <eLiterals name="normal" value="3"/>
    <eLiterals name="major" value="4"/>
    <eLiterals name="critical" value="5"/>
    <eLiterals name="blocker" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Priority">
    <eLiterals name="P1"/>
    <eLiterals name="P2" value="1"/>
    <eLiterals name="P3" value="2"/>
    <eLiterals name="P4" value="3"/>
    <eLiterals name="P5" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Status">
    <eLiterals name="NEW"/>
    <eLiterals name="ASSIGNED" value="1"/>
    <eLiterals name="RESOLVED" value="2"/>
    <eLiterals name="CLOSED" value="3"/>
    <eLiterals name="REOPENED" value="4"/>
    <eLiterals name="VERIFIED" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Resolution">
    <eLiterals name="FIXED"/>
    <eLiterals name="INVALID" value="1"/>
    <eLiterals name="WONTFIX" value="2"/>
    <eLiterals name="DUPLICATE" value="3"/>
    <eLiterals name="WORKSFORME" value="4"/>
    <eLiterals name="NOT_ECLIPSE" value="5"/>
  </eClassifiers>
</ecore:EPackage>
